[tool.poetry]
name = "astronvim-test"
version = "0.1.0"
description = ""
authors = ["bonifacius <become.lev.03@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
aiogram = "^3.13.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
